"""The Python model against the recorded-trajectory fixture.

The fixture was generated by the retired C++ model, so this is a regression
check against a recorded answer, not two implementations agreeing -- that
second implementation is gone. It still catches a change in the numbers; it no
longer corroborates them."""

import os

import numpy as np
import pytest
from crane_model import CraneModel, CraneModelError, ErrorCode, Frame, Payload, Tool

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CONFIG = os.path.join(ROOT, "config", "hydraulics.yaml")
TOLERANCE_M = 1e-9

DESCRIPTION = os.path.join(HERE, "description", "pzs100.urdf")


def build(tool):
    with open(DESCRIPTION, encoding="utf-8") as handle:
        return CraneModel(handle.read(), tool, hydraulics_config=CONFIG)


@pytest.fixture(scope="module")
def fixture_rows():
    path = os.path.join(HERE, "recorded_parity_fixture.txt")
    with open(path, encoding="utf-8") as handle:
        rows = [
            line.split() for line in handle if line.strip() and not line.startswith("#")
        ]
    return np.array(rows, dtype=float)


@pytest.mark.parametrize(
    "frame,columns",
    [
        (Frame.ROTATOR_LOWER_PART, slice(18, 21)),
        (Frame.TIP, slice(30, 33)),
    ],
)
def test_forward_kinematics_matches_the_recorded_fixture(fixture_rows, frame, columns):
    model = build(Tool.PZS100)
    for row in fixture_rows:
        pose = model.forward_kinematics(row[2:10], Frame.MOUNTING_BASE, frame)
        assert np.allclose(pose.position_m, row[columns], atol=TOLERANCE_M)


def test_k8_orientation_matches_the_recorded_fixture(fixture_rows):
    model = build(Tool.PZS100)
    for row in fixture_rows:
        pose = model.forward_kinematics(
            row[2:10], Frame.MOUNTING_BASE, Frame.ROTATOR_LOWER_PART
        )
        assert np.allclose(
            pose.as_matrix()[:3, :3], row[21:30].reshape(3, 3), atol=1e-9
        )


def test_the_telescope_moves_the_tool_twice():
    """q5_small_telescope mimics q4: the tool travels 2*q4, Jacobian column 3
    carries both stages. Issue 030."""
    model = build(Tool.PZS100)
    q = np.zeros(8)
    rest = model.forward_kinematics(q, Frame.MOUNTING_BASE, Frame.TCP).position_m
    q[3] = 0.4
    out = model.forward_kinematics(q, Frame.MOUNTING_BASE, Frame.TCP).position_m
    assert np.linalg.norm(out - rest) == pytest.approx(0.8, abs=1e-9)
    assert np.linalg.norm(model.jacobian(q, Frame.TCP).value[:, 3]) == pytest.approx(
        2.0, abs=1e-9
    )


def test_the_rotator_wraps_rather_than_stopping(fixture_rows):
    """The recordings reach -7.8 rad on theta8, well outside one turn: the joint
    is `continuous` and the model must take it as given."""
    rotator = fixture_rows[:, 8]
    assert rotator.min() < -np.pi
    model = build(Tool.PZS100)
    q = np.zeros(8)
    q[6] = rotator.min()
    wrapped = q.copy()
    wrapped[6] = rotator.min() + 2.0 * np.pi
    assert np.allclose(
        model.forward_kinematics(q, Frame.MOUNTING_BASE, Frame.TCP).position_m,
        model.forward_kinematics(wrapped, Frame.MOUNTING_BASE, Frame.TCP).position_m,
        atol=1e-12,
    )


def test_a_description_without_the_canonical_joints_is_refused():
    with pytest.raises(CraneModelError) as refusal:
        CraneModel(
            '<robot name="stub"><link name="only"/></robot>',
            Tool.PZS100,
            hydraulics_config=CONFIG,
        )
    assert refusal.value.code in (
        ErrorCode.MISSING_JOINT,
        ErrorCode.INVALID_ROBOT_DESCRIPTION,
    )


def test_a_non_finite_configuration_is_refused():
    model = build(Tool.PZS100)
    q = np.zeros(8)
    q[2] = np.nan
    with pytest.raises(CraneModelError) as refusal:
        model.forward_kinematics(q, Frame.MOUNTING_BASE, Frame.TCP)
    assert refusal.value.code is ErrorCode.NON_FINITE_INPUT


def test_passive_equilibrium_matches_the_recorded_fixture(fixture_rows):
    model = build(Tool.PZS100)
    for row in fixture_rows:
        settled = model.passive_equilibrium(CraneModel.actuated(row[2:10]))
        assert np.allclose(settled, row[47:49], atol=1e-9)


def test_the_equilibrium_is_the_hanging_well_and_not_the_standing_saddle(fixture_rows):
    """h_u = 0 also has the tool standing up; the stiffness sign tells them
    apart, so the answer must be a minimum."""
    model = build(Tool.PZS100)
    for row in fixture_rows[:8]:
        q_a = CraneModel.actuated(row[2:10])
        settled = model.passive_equilibrium(q_a)
        q = np.zeros(8)
        q[[0, 1, 2, 3, 6, 7]] = q_a
        _, stiffness, _ = model._passive_gravity(q, settled)
        np.linalg.cholesky(stiffness)  # raises if the answer is a saddle


def test_a_configuration_with_nowhere_to_hang_is_refused():
    """Where pi/2 - (q2 + q3) leaves the tip joint's +-pi/2 range the tool rests
    on a stop rather than hangs; a plausible q_u is worse than none. Issue 032."""
    model = build(Tool.PZS100)
    q_a = np.array([0.0, -1.2, -0.91, 0.0, 0.0, 0.0])
    assert abs(np.pi / 2.0 - (q_a[1] + q_a[2])) > np.pi / 2.0
    with pytest.raises(CraneModelError) as refusal:
        model.passive_equilibrium(q_a)
    assert refusal.value.code is ErrorCode.SINGULAR_CONFIGURATION


def test_a_payload_changes_where_the_tool_hangs():
    model = build(Tool.PZS100)
    q_a = np.array([0.2, 0.7, 0.4, 1.0, -1.5, 0.3])
    bare = model.passive_equilibrium(q_a)
    loaded = model.passive_equilibrium(
        q_a,
        Payload(
            mass_kg=400.0, center_of_mass_k8_m=np.array([0.3, 0.0, -0.5]), valid=True
        ),
    )
    assert not np.allclose(bare, loaded, atol=1e-6)
    # The payload is restored after the call, so the next answer is the bare one.
    assert np.allclose(model.passive_equilibrium(q_a), bare, atol=1e-12)
