"""The checked-in URDF fixture against the description it was expanded from.

`crane_mpc`'s `export_ocp.py --check` regenerates the solver from this
snapshot, so it cannot see the snapshot itself falling behind
`epsilon_crane_description`. That is how the pre-fit damping stayed baked into
the shipped solver for four days. This test closes that gap: it re-expands the
live xacro with the launch file's own arguments and demands the fixture match
it byte for byte.
"""

import difflib
import importlib.util
import os
import subprocess

from ament_index_python.packages import (
    PackageNotFoundError,
    get_package_share_directory,
)

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LAUNCH = os.path.join(ROOT, "launch", "update_test_descriptions.launch.py")
FIXTURE = os.path.join(HERE, "description", "pzs100.urdf")
REGENERATE = "ros2 launch crane_model update_test_descriptions.launch.py"
BANNER = "autogenerated by xacro from"


def _launch_module():
    """Import the launch file for its xacro arguments -- one source, not two."""
    spec = importlib.util.spec_from_file_location("update_test_descriptions", LAUNCH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _lines(path):
    """Read, minus xacro's provenance banner -- it stamps its own input path."""
    with open(path, encoding="utf-8") as handle:
        return [line for line in handle if BANNER not in line]


def test_fixture_matches_the_live_description(tmp_path):
    module = _launch_module()
    # Not a skip. This is the only thing tying the fixture -- and through it the
    # shipped acados solver -- to the description, and a guard that reports
    # success when it could not look is worse than no guard.
    try:
        share = get_package_share_directory(module.DESCRIPTION_PACKAGE)
    except PackageNotFoundError as error:
        raise AssertionError(
            f"{module.DESCRIPTION_PACKAGE} is not on the ament index, so the "
            "fixture could not be checked against it"
        ) from error

    output = tmp_path / "pzs100.urdf"
    subprocess.run(
        ["xacro", os.path.join(share, "urdf", module.DESCRIPTION_FILE)]
        + list(module.XACRO_ARGUMENTS)
        + [f"tool:={module.TOOL}", "-o", str(output)],
        check=True,
    )

    current = _lines(FIXTURE)
    live = _lines(output)

    diff = list(
        difflib.unified_diff(current, live, fromfile="fixture", tofile="description")
    )
    assert not diff, (
        f"test/description/pzs100.urdf is behind {module.DESCRIPTION_PACKAGE}. "
        f"Regenerate it with `{REGENERATE}` and re-export the solver.\n" + "".join(diff)
    )
