#!/usr/bin/env python3
"""
Generate the C `test/test_symbolic_parity.cpp` compares the Python model against.

`scripts/crane_symbolic.py` is the model; this is the one thing in the package
that turns it into an artefact. It runs CasADi's code generation on the dynamics,
the output map, the transmission, the damping and the mimic projection of both
descriptions, and checks the result in -- following
`scripts/derive_collision_model.py` and `test/derive_recorded_parity.py`, both of
which check their output in for the same reason: the expensive step happens once,
by hand, and the test then compares against a file rather than against a
toolchain.

    ./scripts/export_model_fixture.py                # rewrite the fixture
    ./scripts/export_model_fixture.py --check        # what the test suite runs

`--check` regenerates into a temporary directory and compares byte for byte. It
is meaningful because CasADi is **pinned** (`wiki/implementation/libraries.md`,
`test/test_casadi_version.cpp`): code generation is version-sensitive, so on an
unpinned toolchain this check would be noise about the toolchain rather than a
statement about the model. When it fails it prints both CasADi version strings
first, because "the model changed" is the second explanation to reach for and not
the first.

`--check` also asserts that importing the model pulled in neither acados nor ROS.
That is a property of the module worth keeping: the parity test must be able to
say the dynamics are right without a solver being installed, let alone correct.

One caveat, because it is easy to read that claim too strongly on this image:
**Pinocchio's Python bindings are delivered through a colcon overlay** here,
`/opt/ros2_ws/install/pinocchio/lib/python3.10/site-packages`, which reaches
`sys.path` only once a colcon `setup.bash` has been sourced. So `import
crane_symbolic` needs that overlay even though it needs nothing out of the ROS
distribution itself. What the assertion below can honestly make is the part that
matters: no `acados`, no `rclpy`, and nothing at all out of `/opt/ros/humble`.

## What is checked in, and why it is spelled `.inc`

`test/generated/` holds two generated files and one hand-written one:

    crane_symbolic_fixture.inc       the generated C
    crane_symbolic_fixture_api.inc   the generated declarations
    crane_symbolic_fixture.c         three lines, hand-written, compiles them

The generated pair does not end in `.c` or `.h` on purpose. Every C and C++ file
in this workspace goes through `ament_cpplint` and `ament_cppcheck`, and a
CasADi-generated translation unit fails them by thousands -- it is machine
output, and reformatting it to pass would make the byte-for-byte check above
compare against whatever the formatter last did rather than against the model.
So the generated text is included rather than compiled directly, and the one
translation unit in that directory is small enough to read.

For the hooks that do not filter by extension the file is instead made a *fixed
point*: trailing whitespace is stripped and the file ends in exactly one newline,
so `trailing-whitespace` and `end-of-file-fixer` have nothing to change and
cannot silently break the regeneration check.
"""

from __future__ import annotations

import argparse
import filecmp
import sys
import tempfile
from pathlib import Path

import casadi as ca

sys.path.insert(0, str(Path(__file__).resolve().parent))

import crane_symbolic as cs  # noqa: E402

# The generator's own name, which is also the basename of both generated files
# and the prefix CasADi gives its internal symbols.
FIXTURE = "crane_symbolic_fixture"

# The ROS distribution, as opposed to the colcon overlay Pinocchio happens to be
# installed into. Nothing the model imports may come out of here. Written as the
# install prefix rather than read from `ROS_DISTRO`, because the check has to
# mean the same thing when that variable is unset -- which is the case it is
# guarding against.
ROS_DISTRIBUTION = "/opt/ros/"

# One description per tool, and the tool name that selects the joint map, the
# tool areas and the jaw transmission out of `config/hydraulics.yaml`. The same
# two files `test_contract`, `test_symbolic_graph` and `test_tool_axis` build
# real models from; they are generated from the machine descriptions and their
# headers carry the `xacro` command that produced them.
DESCRIPTIONS = (
    ("pzs100", "pzs100.urdf"),
    ("epsilon7040", "epsilon_7040.urdf"),
)

# Prepended to both generated files. No date, no host and no path outside the
# package: the whole point is that two runs on two machines produce the same
# bytes.
BANNER = """/* Generated by crane_model/scripts/export_model_fixture.py -- do not edit.
 *
 * The Python symbolic model of `scripts/crane_symbolic.py`, code-generated so
 * that `test/test_symbolic_parity.cpp` can compare it against the numeric
 * `crane_model` without a Python interpreter, without acados and without a
 * solver. Regenerate with
 *
 *     ./scripts/export_model_fixture.py
 *
 * and never by hand: `--check` asserts that a no-op run reproduces this file
 * byte for byte, and an edit here is a difference between the model and its
 * artefact that nothing else would report.
 */
"""


def build(description_dir: Path) -> ca.CodeGenerator:
    """
    Add every function of both descriptions to one generator.

    One generator and not two because the two share CasADi's internal symbol
    prefix and its sparsity tables, so a single translation unit is both smaller
    and simpler to compile than a pair that would have to be kept apart.
    """
    generator = ca.CodeGenerator(FIXTURE + ".c", {"with_header": True})
    for tool, description in DESCRIPTIONS:
        model = cs.CraneSymbolicModel((description_dir / description).read_text(), tool)
        for function in model.functions(tool):
            generator.add(function)
    return generator


def normalise(text: str) -> str:
    """Make the generated text a fixed point of the whitespace hooks."""
    lines = [line.rstrip() for line in text.replace("\r\n", "\n").split("\n")]
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines) + "\n"


def generate(description_dir: Path, output_dir: Path) -> list:
    """Write the fixture into `output_dir` and return the files written."""
    output_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as scratch:
        build(description_dir).generate(str(Path(scratch)) + "/")
        written = []
        for suffix, target in ((".c", ".inc"), (".h", "_api.inc")):
            source = Path(scratch) / (FIXTURE + suffix)
            path = output_dir / (FIXTURE + target)
            path.write_text(BANNER + normalise(source.read_text()))
            written.append(path)
    return written


def versions() -> str:
    """
    Both of CasADi's version strings, which are not the same string.

    `casadi.__version__` is `git describe` off an unpinned build and names a tag
    the build is not; `CasadiMeta.version()` is what was compiled. Issue 067's
    notes are the long form of why a mismatch here reads as two installs when it
    is one.
    """
    return (
        f"casadi.__version__            {ca.__version__}\n"
        f"casadi.CasadiMeta.version()   {ca.CasadiMeta.version()}\n"
        f"casadi.CasadiMeta.git_revision()  {ca.CasadiMeta.git_revision()}"
    )


def check_imports() -> None:
    """
    Refuse a model that imported acados or ROS to get itself built.

    Two ways of asking, because neither catches the other: a name list, which is
    what a stray `from acados_template import ...` at the top of the module would
    trip; and where every module that *did* load came from, which is what a
    transitive ROS import would trip whatever it is called.
    """
    by_name = {
        name.split(".")[0]
        for name in sys.modules
        if name.split(".")[0]
        in {"acados_template", "acados", "rclpy", "ament_index_python", "rosbag2_py"}
    }
    by_origin = {
        name.split(".")[0]
        for name, module in sys.modules.items()
        if isinstance(getattr(module, "__file__", None), str)
        and module.__file__.startswith(ROS_DISTRIBUTION)
    }
    forbidden = sorted(by_name | by_origin)
    if forbidden:
        raise SystemExit(
            "crane_symbolic pulled in " + ", ".join(forbidden) + ", so the parity "
            "test would need a solver or a ROS installation to say whether the "
            "dynamics are right"
        )


def main() -> int:
    package = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument(
        "--descriptions",
        type=Path,
        default=package / "test" / "description",
        help="where the two expanded machine descriptions are",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=package / "test" / "generated",
        help="where the fixture is checked in",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate into a temporary directory and compare, writing nothing",
    )
    arguments = parser.parse_args()

    check_imports()

    if not arguments.check:
        for path in generate(arguments.descriptions, arguments.output):
            print(f"wrote {path}")
        return 0

    with tempfile.TemporaryDirectory() as scratch:
        fresh = generate(arguments.descriptions, Path(scratch))
        stale = [
            path for path in fresh if not _same(arguments.output / path.name, path)
        ]
    if not stale:
        print(f"fixture in {arguments.output} is what this model generates")
        return 0

    print(versions())
    print()
    for path in stale:
        print(
            f"{arguments.output / path.name} is not what this model generates. "
            "Check the two CasADi readings above against the pinned version "
            "before concluding that the model changed; if they agree, rerun "
            "./scripts/export_model_fixture.py and read the diff."
        )
    return 1


def _same(checked_in: Path, fresh: Path) -> bool:
    return checked_in.is_file() and filecmp.cmp(checked_in, fresh, shallow=False)


if __name__ == "__main__":
    sys.exit(main())
